helm:
  parameters:
  - name: image.name
    value: ghalamif/imagefaps
    forcestring: true
  - name: image.tag
    value: 0.1.12
    forcestring: true
  - name: backend.image.repository
    value: ghalamif/imagefaps
    forcestring: true
  - name: backend.image.tag
    value: 2.0.6
    forcestring: true
