apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: recreate-Rollout
spec:
  replicas: 3
  selector:
    matchLabels:
      app: recreate-Rollout-pod
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: recreate-Rollout-pod
    spec:
      containers:
      - name: rollouts-demo
        image: argoproj/rollouts-demo:yellow
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        resources:
          requests:
            memory: 32Mi
            cpu: 5m