apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: basic-app
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/ghalamif/faps.git
    targetRevision: HEAD
    path: basic-app
  destination: 
    server: https://kubernetes.default.svc
    namespace: basic-app

  syncPolicy:
    syncOptions:
      - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-rollout-app
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/ghalamif/faps.git
    targetRevision: HEAD
    path: argo-rollout
  destination: 
    server: https://kubernetes.default.svc
    namespace: argo-rollout-app

  syncPolicy:
    syncOptions:
      - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kustomize-app
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/ghalamif/faps.git
    targetRevision: HEAD
    path: kustomize-app/base
  destination: 
    server: https://kubernetes.default.svc
    namespace: my-kustomize-app

  syncPolicy:
    syncOptions:
      - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-app
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/ghalamif/faps.git
    targetRevision: HEAD
    path: helm-app/helmrollout
    helm:
      #releaseName: sealed-secrets
      valueFiles:
        - values.yaml
  destination: 
    server: https://kubernetes.default.svc
    namespace: my-helm-app

  syncPolicy:
    syncOptions:
      - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-hooks
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/ghalamif/faps.git
    targetRevision: HEAD
    path: argo-hooks
  destination: 
    server: https://kubernetes.default.svc
    namespace: my-argo-hooks-app

  syncPolicy:
    syncOptions:
      - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true

