apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp-argo-application
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/ghalamif/faps.git
    targetRevision: HEAD
    path: dev
  destination: 
    server: https://kubernetes.default.svc
    namespace: myapp

  syncPolicy:
    syncOptions:
      - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
      #autoSync: true
      #syncInterval: 1m


---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: base-app
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/ghalamif/faps.git
    targetRevision: HEAD
    path: baseapp
  destination: 
    server: https://kubernetes.default.svc
    namespace: my-base-app

  syncPolicy:
    syncOptions:
      - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
      #autoSync: true
      #syncInterval: 1m


---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kustomizeapp-app
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/ghalamif/faps.git
    targetRevision: HEAD
    path: kustomizeapp
  destination: 
    server: https://kubernetes.default.svc
    namespace: my-kustomizeapp-app

  syncPolicy:
    syncOptions:
      - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
      #autoSync: true
      #syncInterval: 1m


---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-app
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/ghalamif/faps.git
    targetRevision: HEAD
    path: helm
  destination: 
    server: https://kubernetes.default.svc
    namespace: my-helm-app

  syncPolicy:
    syncOptions:
      - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
      #autoSync: true
      #syncInterval: 1m


---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argorollout-app
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/ghalamif/faps.git
    targetRevision: HEAD
    path: argo-rollout
  destination: 
    server: https://kubernetes.default.svc
    namespace: my-argorollout-app

  syncPolicy:
    syncOptions:
      - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
      #autoSync: true
      #syncInterval: 1m
---