apiVersion: apps/v1
kind: Deployment
metadata:
  name: argo-hooks-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: argo-hooks
  template:
    metadata:
      labels:
        app: argo-hooks
    spec:
      containers:
      - name: argo-hooks
        image: nginx:1.23.4
        env:
          - name: S_W_TOKEN
            valueFrom:
              secretKeyRef:
                name: slack-notification-secret  # The name of the Secret created by the SealedSecret
                key: webhook-token   
          - name: S_TOKEN
            valueFrom:
              secretKeyRef:
                name: slack-notification-secret  # The name of the Secret created by the SealedSecret
                key: token         
        resources:
          limits:
            memory: "26Mi"
            cpu: "5m"
        ports:
        - containerPort: 80
