apiVersion: apps/v1
kind: Deployment
metadata:
  name: argo-hooks-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: argo-hooks
  template:
    metadata:
      labels:
        app: argo-hooks
    spec:
      containers:
      - name: argo-hooks
        image: ghalamif/faps:green
        resources:
          limits:
            memory: "26Mi"
            cpu: "5m"
        ports:
        - containerPort: 80
