apiVersion: batch/v1
kind: Job
metadata:
  generateName: app-slack-notification-
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      containers:
      - name: slack-notification
        image: ghalamif/faps:green
        command: ["sh", "-c"]
        args:
          - 'curl -X POST -H "Content-type: application/json" --data "{\"text\":\"xxx, World!\"}" https://hooks.slack.com/services/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'
      restartPolicy: Never
  backoffLimit: 2