apiVersion: batch/v1
kind: Job
metadata:
  generateName: app-slack-notification-
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      containers:
      - name: slack-notification
        image: ghalamif/faps:green
        command:
          - "sh"
          - "-c"
          - 'curl -X POST -H "Content-type: application/json" --data "{\"text\":\"ArgoCD PostSync Hook Succeeded!\"}" https://hooks.slack.com/services/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'
      restartPolicy: Never
  backoffLimit: 2