apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: secrets
  namespace: my-argo-hooks-app
spec:
  encryptedData:
    token: AgCGdI4WWhhqJkG3ceX6IiGB3aZEaeLcBRruXBw17GzfR+KJIEkEKQhJ7c8d4NWHEscfc6W8iL+T17tOBOVBdo1rMbi52+/yf+Rpo4nOlmYUBR3Xuid/KuRhWqJyfN+UgqsEbSwEwd+X2oikyLD+mKMO6UfD49kycMAAw2yqJINlZ/eF2hnUvBWZnNB3720W7cLMxfukOlKVbpy3hQFrehgwpKRM2/iLU4F8KJj5092Rk6LVbpSMceA92/q1yRgJBqHJ9o5NKM4IFnUWn3m3xhYfIIt8hn0uapgsO6Q55BpUPyyvBX5iuiduzSJYuf6zH9jSVXeKXZugR68TMXsn03NKHJAAN91KecPG/OjA9wz+PWoC3/licPIutQjgLvcpdmYHvcwkPjUqZYjAspXpLoo0QGc3kq8HDXQzfpdjb8Y6Q+bA1Vp1XRRRG1oWnh4RYXasqZc5acS4Ryg6DPMP1tfKReBdbLUckEFJLALaODL6qyolmr/TJ6p31pBna/c0EfWL7EZwLpmfd6aPLCgsTqJCk2P/OT2fODN6+XDkKtKu+2wpZVBN6gRlrb3pV5Vu8UpQO6D/Q5zUQw3M+TEU1KKUkBcFumeAKgGzAiOu/1W1bXmlMY7yHANjPiQbNMhlQGjCB3j9Ppo3oEYh99NIATFHG6bndVRp3KVi+kGWoiDq3of/MOFZtq2M7TwtWx0YC1ehcQ5GJXTbx+NPhHAVAnbP02AVsN1urpkEmPlMnLOAlCZFlyGPVrFx+LNnQH0Wdqx1QcXeueHQfA==
  template:
    metadata:
      creationTimestamp: null
      name: secrets
      namespace: my-argo-hooks-app
    type: Opaque