apiVersion: apps/v1
kind: Deployment
metadata:
  name: faps-deployment
spec:
  selector:
    matchLabels:
      app: faps
  replicas: 1
  template:
    metadata:
      labels:
        app: faps
    spec:
      containers:
      - name: faps
        image: ghalamif/imagefaps:0.1.0
        resources:
          limits:
            memory: "12Mi"
            cpu: "5m"
        ports:
        - containerPort: 80
