apiVersion: v1
kind: Service
metadata:
  name: base-helm-app-service
spec:
  selector:
    app: {{.value.base.dep.appName | quote}}
  ports:
    - port: {{.value.base.svc.port}}
      targetPort: {{.value.base.svc.targetPort}}

